### ISSUE TITLE
Hand-pressed paper broken

### ISSUE THREAD

**Issue by TheLeopold** [DesertRose2/desertrose#470]
## Reproduction:
1. Make a hand-pressed paper (50u water, wooden plank, hatchet)
2. Try to get a paper from it.
3. You can't

**Comment by SabreML** [comment]
Unable to reproduce with a wooden plank, bucket of water, and a hatchet.
![Dos3lpNXx5](https://user-images.githubusercontent.com/57483089/118190605-4a723180-b43b-11eb-8de5-308b13e9d7c3.gif)

**Comment by TheLeopold** [comment]
Can you take an actual paper by clicking on it? I couldn't when checked last time.

**Comment by SabreML** [comment]
Ah sorry, I misunderstood the issue.
Looks like the paper bundle is just overriding the 'take a paper' code altogether, rather than adding a check onto it.
https://github.com/DesertRose2/desertrose/blob/837c2086a63bc835f38c58b1bdfe13f90d454e29/code/modules/paperwork/paperbin.dm#L154-L156
Working on a fix now.
