### ISSUE TITLE
Legion Lance seems to do the less damage now.

### ISSUE THREAD

**Issue by csmrookie** [DesertRose2/desertrose#619]
During the start of the round I hopped on as Formica Cutler for the role on Recruit Decanus, choosing Princpes loadout, which included the legion lance. Usually when using the legion lance two handed, you can take out ghoul reavers in two hits or the fiends with regular glaives in two hits, but now it takes three hits to kill a fiend with a legion lance, and three hits to kill a ghoul reaver with a legion lance. I wonder if this was a bit of a misstep or that the mobs were buffed up to take more hits now. For evidence, I went out to kill two super mutants with a legion lance, which should have ended in four hits but ended in five. Then I did the super mutant with the rifle with a regular old glaive, which took seven hits to kill. If it were with a legion lance, it would've been six, so yeah. Just wondering if this was some sort of mistake.

**Comment by panzer1944** [comment]
#616 made this happen. It's not a mistake, big-leagues and buffout were broken OP before due to a bug in how it worked. This PR, 616, fixed big-leagues to the more intended value while still keeping melee strong and viable. I understand not one-shotting or 2shotting certain ghouls is fucking PAIN, which is why im going to look at ghoul-health eventually, since they really shouldnt be tanking 7 556 shots and still be swinging.
